### ISSUE TITLE
Implement Output result after multigrid

### ISSUE THREAD

**Issue by TimoH447** [hpc2-2024/programming-project-awesome_team#26]
After execution the program should print out all important arguments which were used:
i.e. grid size N, levels, dimension, smoother used, ...
and the results:
i.e. Number of iterations, error, is converged.

**Comment by Jupyter01** [comment]
Added the following outputs: 
- grid size N 
- number of grids, levels
- dimension 
- number of smoothing operations, v
- whether F-cycle is used or not 

- Number of iterations
- final error
- whether the algorithm converged or not
- average time over multiple runs (if specified)
- time of single run (if specified)

**Comment by TimoH447** [comment]
Wollen wir das in den Main mergen?
